# -- Configuracao do site --

baseURL = "https://caxingueles.eco.br/"
defaultContentLanguage = "pt-br"

enableRobotsTXT = true
summaryLength = 0

[pagination]
  pagerSize = 10

[taxonomies]
  categoria = "categorias"

[outputs]
  home = ["HTML", "RSS"]

[privacy]
  [privacy.youTube]
    privacyEnhanced = true
