locale = "pt-BR"
label = "Português"
direction = "ltr"
weight = 1

title = "Caxinguelês"
copyright = "Textos da Turma 12 — CC BY-NC-SA 4.0"

[params]
  description = "Escritos da Turma 12 do mestrado da ESCAS — Instituto de Pesquisas Ecológicas"
