# Tarefa 2 — Início, cards e cores por categoria.
tem "$T" index.html 'class="hero hero--destaque"'
tem "$T" index.html '<h1 class="hero__titulo" id="hero-titulo">Caxinguelês</h1>'
tem "$T" index.html 'class="grade-posts"'
tem "$T" index.html '<article class="card-post" data-ipe="roxo">'
tem "$T" index.html '<article class="card-post">'
tem "$T" index.html 'class="card-post__img" src="/grafismos/ipe-roxo.svg" alt="Flor de ipê roxo"'
tem "$T" index.html '<p class="card-post__resumo">Resumo do fixture completo.</p>'
tem "$T" index.html '<p class="card-post__meta">Autora de Teste · '
tem "$T" index.html 'class="chips"'
tem "$T" index.html 'data-ipe="roxo" href="/categorias/turma/"'
tem "$T" index.html 'href="/categorias/avulsa/"'
nao_tem "$T" index.html 'data-ipe=""'
nao_tem "$T" index.html 'src=""'
nao_tem "$T" index.html '<p class="card-post__resumo"></p>'
nao_tem "$T" index.html 'class="card-post__meta"> · '
nao_tem "$T" index.html 'class="estado-vazio"'
# Produção: sem textos publicados, a Início mostra o estado vazio e nenhum fixture.
tem "$P" index.html 'class="estado-vazio"'
nao_tem "$P" index.html 'grade-posts'
nao_tem "$P" index.html 'Fixture'
# Início: só o título, sem rótulo acima, e o texto de apresentação com link para "O nome" no Sobre.
nao_tem "$T" index.html 'class="hero__rotulo"'
tem "$T" index.html '<p>Este é o espaço dos registros e publicações da Turma 12* do mestrado profissional da ESCAS — Escola Superior de Conservação Ambiental e Sustentabilidade, do Instituto de Pesquisas Ecológicas.</p>'
tem "$T" index.html '<p class="hero__meta" style="margin-top: var(--esp-4)">* Iniciativa independente dos mestrandos, sem vínculo oficial com a ESCAS ou o IPÊ.</p>'
nao_tem "$T" index.html 'Autointitulados'
tem "$T" sobre/index.html 'id="o-nome"'
