# Tarefa 4 — página de post.
F=publicacoes/fixture-completo/index.html
tem "$T" "$F" '<article data-ipe="roxo">'
tem "$T" "$F" 'class="post-cabecalho"'
tem "$T" "$F" '<a class="tag" href="/categorias/turma/">Turma</a>'
tem "$T" "$F" '<h1>Fixture completo</h1>'
tem "$T" "$F" 'por Autora de Teste · '
tem "$T" "$F" '<time datetime="2026-09-20">'
tem "$T" "$F" 'de setembro de 2026'
tem "$T" "$F" 'min de leitura'
tem "$T" "$F" '<figure class="post-capa">'
tem "$T" "$F" 'Legenda da capa de teste'
tem "$T" "$F" '<details class="post-sumario" open>'
tem "$T" "$F" 'href="#primeira-seção"'
tem "$T" "$F" '<blockquote class="citacao">'
tem "$T" "$F" '<figure class="figura">'
tem "$T" "$F" '<figcaption>Figura 1. Legenda de teste.</figcaption>'
nao_tem "$T" "$F" '<p><figure'
tem "$T" "$F" '<aside class="destaque"'
tem "$T" "$F" 'Texto do destaque de teste.'
tem "$T" "$F" '<section class="referencias"'
tem "$T" "$F" '<em>Periódico de Teste</em>'
tem "$T" "$F" 'data-copiar'
tem "$T" "$F" 'href="https://wa.me/?text='
S=publicacoes/fixture-sem-categoria/index.html
tem "$T" "$S" '<article>'
tem "$T" "$S" '<p class="post-meta"><time'
tem "$T" "$S" 'src="/grafismos/folha-2.svg"'
nao_tem "$T" "$S" 'class="figura"'
nao_tem "$T" "$S" 'class="post-capa"'
nao_tem "$T" "$S" 'class="post-sumario"'
nao_tem "$T" "$S" 'class="referencias"'
nao_tem "$T" "$S" 'class="tag"'
# Produção: o rascunho não vai para o ar.
nao_existe "$P" publicacoes/primeiro-texto/index.html
